apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.1.0 (36652f6)
  creationTimestamp: null
  labels:
    io.kompose.service: forumdb
  name: forumdb
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: forumdb
    spec:
      containers:
      - env:
        - name: POSTGRES_DB
          value: forum
        - name: POSTGRES_PASSWORD
          value: pass
        - name: POSTGRES_USER
          value: user
        image: postgres:10-alpine
        name: forumdb
        resources: {}
      restartPolicy: Always
status: {}
